datasources:
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    basicAuth: false
    readOnly: false
  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    basicAuth: false
    readOnly: false
